### ISSUE TITLE
dot invisible in console

### ISSUE THREAD

**Issue by Valve** [larsenwork/monoid#90]
<img width="1254" alt="machine_ _valentin_macbook-pro____projects_evrone_machine_ _zsh_ _180x42" src="https://cloud.githubusercontent.com/assets/27387/8934045/58760df0-354e-11e5-87cf-4dc0dd2660b4.png">

I'm running RSpec test suite and it usually prints a lot of green dots, but with this font most of the dots are  invisible.
I'm using Monoid Retina 14pt on a stock terminal app. The character code is 46 (ascii dot).

**Comment by larsenwork** [comment]
Cheers, when did you download the font? I tried fixing this 5 hrs ago: https://github.com/larsenwork/monoid/commit/60f0fd692b2e9d2d29dba6ae0bf58b235972667e

**Comment by larsenwork** [comment]
Ah, nevermind - I can I missed it for Retina (regular should work). 
I'm currently finishing 0.55 so this should be fixed by the end of the day (Denmark time)

**Comment by Valve** [comment]
@larsenwork awesome, thanks :+1:

**Comment by Valve** [comment]
Hey @larsenwork , I've upgraded to 0.55 and the issue still remains.

**Comment by larsenwork** [comment]
Strange - the ligatures in retina and regular are created in the exact same way. You are certain it's not stuck in in your font cache or something? 
![screen shot 2015-07-29 at 09 40 32](https://cloud.githubusercontent.com/assets/3859425/8952279/e671d8b4-35d5-11e5-8b5e-95ad3d09b79a.png)

**Comment by Valve** [comment]
@larsenwork , it started working after reboot. On a side note, I'm using MacBook Pro retina with Monoid Retina and it looks perfect. But I often connect external Dell monitor (1920x1080). and the font starts looking a big fuzzy. What's the main difference between retina vs regular variants and should I change fonts to regular when connecting an external monitor?

**Comment by larsenwork** [comment]
:+1: Retina is optimised for HDPI displays. 
https://youtu.be/hdld21mlzbY?t=34m35s
